load('S:\Lab-Shared\Experiments\N1P2\Analysis\MixedModel\theTable')

formulasExp3 = {'Voltage ~ isN1 + isP2 - 1 + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2 + (isN1 + isP2 + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2 + dist_mean:size_jump):spread + dist_mean:size_jump + (1|subject)',...
                'Voltage ~ isN1 + isP2 - 1 + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2 + (isN1 + isP2 + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2):spread + dist_mean:size_jump + (1|subject)',...                
                'Voltage ~ isN1 + isP2 - 1 + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2 + (isN1 + isP2 + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2):spread + (1|subject)',...
                'Voltage ~ isN1 + isP2 - 1 + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2 + (isN1 + isP2 + dist_mean:isN1 + size_jump:isN1 + size_jump:isP2):spread + (1|subject)',...
                'Voltage ~ isN1 + isP2 - 1 + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2 + (isN1 + dist_mean:isN1 + size_jump:isN1 + size_jump:isP2):spread + (1|subject)',...
                'Voltage ~ isN1 + isP2 - 1 + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2 + (isN1 + dist_mean:isN1 + size_jump:isN1):spread + (1|subject)',...
                'Voltage ~ isN1 + isP2 - 1 + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2 + (isN1 + dist_mean:isN1):spread + (1|subject)',...
                };
            
formulas = {'Voltage ~ Potential*dist_mean + Potential*size_jump + dist_mean:size_jump + (1|subject) + (1|ExpN)',...
            'Voltage ~ Potential*dist_mean + Potential*size_jump + (1|subject) + (1|ExpN)',...
            'Voltage ~ Potential*dist_mean + size_jump + (1|subject) + (1|ExpN)',...
            'Voltage ~ Potential*dist_mean + (1|subject) + (1|ExpN)',...
            'Voltage ~ Potential*size_jump + (1|subject) + (1|ExpN)',...
            'Voltage ~ Potential + dist_mean:isN1 + dist_mean:isP2 + (1|subject) + (1|ExpN)',...
            'Voltage ~ Potential + size_jump:isN1 + size_jump:isP2 + (1|subject) + (1|ExpN)',...
            'Voltage ~ Potential + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2 + dist_mean:size_jump + (1|subject) + (1|ExpN)',...
            'Voltage ~ Potential + dist_mean:isN1 + dist_mean:isP2 + size_jump:isN1 + size_jump:isP2 + (1|subject) + (1|ExpN)',...
            };

lmes = cell(length(formulas),1);
for i=1:length(formulas)
    disp(i)
    %lmes{i} = fitlme(theTable(theTable.ExpN==categorical(3),:),formulas{i});
    lmes{i} = fitlme(theTable,formulas{i});
end
lmess = cell(length(formulasExp3),1);
for i=1:length(formulasExp3)
    disp(i)
    lmess{i} = fitlme(theTable,formulasExp3{i},'Exclude',theTable.ExpN~=3);
end
%lmeslmese = fitlme(theTable,formulas);